try:
    print('one')
    print('two')
except:
    print('three')
finally:
     print('four')           #o/p is one,two,three
                              #exception handling is unexpected and unwanted errors